## kNN의 Classification

In [2]:
import pandas as pd

In [3]:
# 데이터 불러오기
iris = pd.read_csv("../Data/iris.csv")
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Name         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
iris.describe()

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [7]:
# Feature와 Target 정의
iris_data = iris.iloc[:,:4]
iris_data.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [8]:
iris_target = iris['Name']
iris_target.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
# Train과 Test 분리 

train_input, test_input, train_target, test_target = train_test_split(
                                                                    iris_data,
                                                                    iris_target,
                                                                    random_state=42,
                                                                    stratify=iris_target
)

In [11]:
# kNN 적용

from sklearn.neighbors import KNeighborsClassifier

In [12]:
# 훈련하기(Trainig)
kn = KNeighborsClassifier()
kn.fit(train_input, train_target)

KNeighborsClassifier()

In [13]:
# 평가하기
kn.score(test_input, test_target)

0.9736842105263158

----
### 최적의 Hyper Parameter 찾기

In [16]:
for i in range(1, 75+1, 2):
    kn = KNeighborsClassifier(n_neighbors=i)
    kn.fit(train_input, train_target)
    print(f"{i} : {kn.score(test_input, test_target)}")

1 : 0.9473684210526315
3 : 0.9736842105263158
5 : 0.9736842105263158
7 : 0.9473684210526315
9 : 0.9736842105263158
11 : 0.9736842105263158
13 : 0.9473684210526315
15 : 0.9473684210526315
17 : 0.9473684210526315
19 : 0.9473684210526315
21 : 0.9473684210526315
23 : 0.9473684210526315
25 : 0.9473684210526315
27 : 0.9210526315789473
29 : 0.9473684210526315
31 : 0.9473684210526315
33 : 0.9210526315789473
35 : 0.9210526315789473
37 : 0.9210526315789473
39 : 0.9210526315789473
41 : 0.9210526315789473
43 : 0.8947368421052632
45 : 0.8947368421052632
47 : 0.8947368421052632
49 : 0.8947368421052632
51 : 0.8947368421052632
53 : 0.8947368421052632
55 : 0.8947368421052632
57 : 0.8947368421052632
59 : 0.8947368421052632
61 : 0.8947368421052632
63 : 0.868421052631579
65 : 0.8947368421052632
67 : 0.9210526315789473
69 : 0.8947368421052632
71 : 0.8947368421052632
73 : 0.8947368421052632
75 : 0.6578947368421053

In [17]:
def kNNF(i):
    kn = KNeighborsClassifier(n_neighbors=i)
    kn.fit(train_input, train_target)
    print(f"{i} : {kn.score(test_input, test_target)}")

In [18]:
for i in range(1, 75+1, 2):
    kNNF(i)

1 : 0.9473684210526315
3 : 0.9736842105263158
5 : 0.9736842105263158
7 : 0.9473684210526315
9 : 0.9736842105263158
11 : 0.9736842105263158
13 : 0.9473684210526315
15 : 0.9473684210526315
17 : 0.9473684210526315
19 : 0.9473684210526315
21 : 0.9473684210526315
23 : 0.9473684210526315
25 : 0.9473684210526315
27 : 0.9210526315789473
29 : 0.9473684210526315
31 : 0.9473684210526315
33 : 0.9210526315789473
35 : 0.9210526315789473
37 : 0.9210526315789473
39 : 0.9210526315789473
41 : 0.9210526315789473
43 : 0.8947368421052632
45 : 0.8947368421052632
47 : 0.8947368421052632
49 : 0.8947368421052632
51 : 0.8947368421052632
53 : 0.8947368421052632
55 : 0.8947368421052632
57 : 0.8947368421052632
59 : 0.8947368421052632
61 : 0.8947368421052632
63 : 0.868421052631579
65 : 0.8947368421052632
67 : 0.9210526315789473
69 : 0.8947368421052632
71 : 0.8947368421052632
73 : 0.8947368421052632
75 : 0.6578947368421053

### n_neighbors = 3이 최적임을 판단

In [21]:
# 훈련하기(Trainig)
kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(iris_data, iris_target)

KNeighborsClassifier(n_neighbors=3)

In [22]:
kn.predict([[5, 2.9, 1, 0.2]])

c:\Users\TJ\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['Iris-setosa'], dtype=object)